version: '3.9'

services:
  database_soujunior:
    image: postgres
    container_name: database_soujunior
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=linkedin_backend
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: linkedIn_Backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
    depends_on:
      database_soujunior:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata:
    driver: local